Лабораторная_1
Polina213/rep-1 pull request #1
Opened 2024-10-19 21:38 UTC by Polina213

2024-10-20 09:37 UTC, rmushkin requested changes
Пожалуйста, поправьте код с учётом [PEP8](https://peps.python.org/pep-0008/). Будут вопросы - пишите!

2024-10-20 09:37 UTC, rmushkin commented on Лабораторная_1/task_1.py
> +numbers[4] = ((sum(numbers[:4])+sum(numbers[5:]))/len(numbers)) # TODO заменить значение пропущенного элемента средним арифметическим
Здорово! Только, пожалуйста, переоформите с учётом [PEP8](https://peps.python.org/pep-0008/) (указаний по стилю написания кода). Вокруг математических операторов должны быть пробелы.

2024-10-20 09:37 UTC, rmushkin commented on Лабораторная_1/task_2.py
> +books_num = int(1.44*1024*1024/100/50/25/4)
[PEP8](https://peps.python.org/pep-0008/): пробелы вокруг оператов нужны.

2024-10-22 21:36 UTC, rmushkin requested changes
Пожалуйста, исправьте микрозамечание и дайте мне доступ на запись в репозиторий, чтобы я мог принять и закрыть.

2024-10-22 21:36 UTC, rmushkin commented on Лабораторная_1/task_1.py
> +numbers[4] = ((sum(numbers[:4]) + sum(numbers[5:])) / len(numbers)) # TODO заменить значение пропущенного элемента средним арифметическим
Проглядел в прошлый раз, видимо...)
[PEP8](https://peps.python.org/pep-0008/):

>  Inline comments should be separated by at least two spaces from the statement.

2024-10-22 22:04 UTC, Polina213 commented
> Пожалуйста, исправьте микрозамечание и дайте мне доступ на запись в репозиторий, чтобы я мог принять и закрыть.

Здравствуйте, отправила Вам приглашение, это то, что нужно было сделать или нет?

2024-10-22 22:51 UTC, rmushkin approved these changes

2024-10-22 22:51 UTC, merged