Лабораторная_2
Polina213/rep-1 pull request #2
Opened 2024-10-26 18:39 UTC by Polina213

Возникли проблемы с заданием 1: у меня получается, что денег хватит на 7 месяцев, хотя правильным ответом является 8. Возрастание цен, как и надо, в первом месяце не учитывается, но со второго уже учитывается.  
Возможно, увеличение цен происходит в конце месяца, тогда, поскольку в первом месяце возрастания не было, и 1, и 2 месяц считаются без учета инфляции? В таком случае всё сходится, но в задаче не уточняется, когда вырастут цены, сказано только то, что в первом месяце роста нет.
Пробовала добавить функцию print(money_capital) и print(spend) в цикл, чтобы программа вывела количество денег в каждом месяце и расходы на следующий за ним, все выглядит максимально логично, скорее всего я немного неправильно поняла задачу.

2024-10-28 18:30 UTC, rmushkin requested changes
Пожалуйста, подумайте ещё чуть-чуть над первой задачей и поправьте вторую.

2024-10-28 18:30 UTC, rmushkin commented on Лабораторная_2/task_1.py
Нет, вы всё правильно поняли, просто всего не учли. Подумайте, пожалуйста, ещё об условии ~~выживания~~выхода в ноль по каждому месяцу.

P. S. PEP8 (всего в одном месте) 😁

2024-10-28 18:30 UTC, rmushkin commented on Лабораторная_2/task_2.py
> +for i in range(months):
Если вы не используете переменную-итератор, то питоничнее называть её `_` (просто одно нижнее подчёркивание). Это точно такая же "буква", как `i`, но сразу видно, что на переменную вам на самом деле наплевать.

2024-10-28 18:30 UTC, rmushkin commented on Лабораторная_2/task_2.py
> +print(f"Подушка безопасности, чтобы протянуть {months} месяцев без долгов:", round(money_capital))
Тут подстава с `round`. Её использовать нельзя; 3 рублей в кармане не хватит, чтобы купить гвоздь за 3,25 рублей. Придётся придумать или найти, как округлять в большую сторону.

2024-10-29 20:25 UTC, Polina213 commented
Добрый вечер, вроде, разобралась с задачкой, спасибо!

2024-10-30 20:58 UTC, merged