Лабораторная_3
Polina213/rep-1 pull request #3
Opened 2024-11-03 20:40 UTC by Polina213

Здравствуйте, во втором задании программа выводит то, что нужно, но при проверке выдает ошибку. Из-за чего это может происходить?

2024-11-06 17:57 UTC, rmushkin commented
> Здравствуйте, во втором задании программа выводит то, что нужно, но при проверке выдает ошибку. Из-за чего это может происходить?

Здравствуйте! Извините, что поздно отвечаю. У вас функция ничего не возвращает, она просто печатает на экран. Это же разные вещи)

2024-11-06 23:06 UTC, Polina213 commented
> Здравствуйте! Извините, что поздно отвечаю. У вас функция ничего не возвращает, она просто печатает на экран. Это же разные вещи)

Вроде разобралась, спасибо!

2024-11-07 20:17 UTC, rmushkin requested changes
Нужно кое-что поправить.

2024-11-07 20:17 UTC, rmushkin commented on Лабораторная_3/task_2.py
> +print("Общие участники:", result)
И как вы думаете, что должна вывести функция, вызванная таким образом?

2024-11-07 20:17 UTC, rmushkin commented on Лабораторная_3/task_3.py
> +    not_letters = [' ', ',', '!', '—', ':', '.', '…', ';', '\n']
`\r` забыли :)
А вообще, в задании указано, что можно пользоваться `.isalpha()`. Это питоничнее, потому что зачем делать то, что за вас уже сделали...

2024-11-07 20:17 UTC, rmushkin commented on Лабораторная_3/task_3.py
> +    symbol_dict = dict()
symbol - это вам не character. А строки состоят как раз из последних.

2024-11-07 20:17 UTC, rmushkin commented on Лабораторная_3/task_3.py
> +    symbol_dict = dict()
Нагляднее делать `{}`, но это не ошибка.

2024-11-07 20:17 UTC, rmushkin commented on Лабораторная_3/task_3.py
> +        frequency[letter] = round(value / summ, 2)
Преждевременное округление. Физический смысл (ещё говорят "бизнес-логика") ничего не говорит об округлении частоты (в отличие, например, от денег из прошлой лабораторной). Поэтому тут округлние - исключительно фишка вывода на экран.

2024-11-07 20:17 UTC, rmushkin commented on Лабораторная_3/task_3.py
> +    print(f'{letter}: {value}')
Вот тут округлению самое место.

2024-11-07 22:15 UTC, Polina213 commented on Лабораторная_3/task_2.py
> +print("Общие участники:", result)
Вот я не понимаю, что не так, ожидаю, что выведет список, но выводит следующее (попросила еще вывести тип переменной result):
Общие участники: []
<class 'list'>

2024-11-07 23:27 UTC, Polina213 commented
Я всё исправила, кроме второго задания, не понимаю, что именно нужно сделать, чтобы программа вывела список

2024-11-08 10:39 UTC, rmushkin requested changes
Третья принимается, в первой маленькая правка. По второму написал отдельно.

2024-11-08 10:39 UTC, rmushkin commented on Лабораторная_3/task_1.py
> +            return i
Смотрите: если нашли, то вернули i, тут всё правильно. А что возвращается, если не нашли?

2024-11-08 10:39 UTC, rmushkin commented on Лабораторная_3/task_2.py
> +print("Общие участники:", result)
Присмотритесь, пожалуйста, к тому, как вы вызываете функцию (какие аргументы и сколько их), а также к тому, какие строчки вы этой функции скармливаете (особенно обратите внимание на разделитель)

2024-11-08 10:39 UTC, rmushkin commented on Лабораторная_3/task_1.py
> +            return i
В первой версии были строчки, которые вы удалили, но напрасно.

2024-11-08 17:59 UTC, rmushkin approved these changes
Принимается ✅

2024-11-08 17:59 UTC, merged